### ISSUE TITLE
Question: Why a special JS file for Drupal?

### ISSUE THREAD

**Issue by pepperstreet** [code-rider/drupal_threesixty_slider#1]
Hello, this is a really interesting project. Just came from the original ThreeSixty project. Many thanks for porting the solution to Drupal.

**Question:**
Just out of curiosity, why does it need a special .JS file? Can you give a short/none-technical explanation, please?

Thanks in advance.

**Comment by code-rider** [comment]
Hi
if you mean why need to create <a href="https://github.com/code-rider/drupal_threesixty_slider">drupal_threesixty_slider</a> and why not we use original <a href="https://github.com/creativeaura/threesixty-slider">threesixty-slider</a>.
so there is a very big reason.
<a href="https://github.com/creativeaura/threesixty-slider">threesixty-slider</a> is not develop for <a href="http://drupal.org/">Drupal(CMS)</a> API.
as a developer i am able to use <a href="https://github.com/creativeaura/threesixty-slider">threesixty-slider</a> because i know about what <a href="https://github.com/creativeaura/threesixty-slider">threesixty-slider</a> needed.
if you see  <a href="https://github.com/creativeaura/threesixty-slider">threesixty-slider</a>
trigger function you need many configuration to run <a href="https://github.com/creativeaura/threesixty-slider">threesixty-slider</a> like this is a <a href="https://github.com/creativeaura/threesixty-slider">threesixty-slider</a> trigger function.

```
function init(){
  product1 = $('.product1').ThreeSixty({
      totalFrames: 72, // Total no. of image you have for 360 slider
      endFrame: 72, // end frame for the auto spin animation
      currentFrame: 1, // This the start frame for auto spin
      imgList: '.threesixty_images', // selector for image list
      progress: '.spinner', // selector to show the loading progress
      imagePath:'assets/product1/', // path of the image assets
      filePrefix: 'ipod-', // file prefix if any
      ext: '.jpg', // extention for the assets
      height: 265,
      width: 400,
      navigation: true,
      disableSpin: true // Default false
  });
}
```

i this case you need to tell the <a href="https://github.com/creativeaura/threesixty-slider">threesixty-slider</a> listed things.
1 . totalFrames: 72, // Total no. of image you have for 360 slider
2 . endFrame: 72, // end frame for the auto spin animation
3 . currentFrame: 1, // This the start frame for auto spin
4 . imgList: '.threesixty_images', // selector for image list
5 . progress: '.spinner', // selector to show the loading progress
6 . imagePath:'assets/product1/', // path of the image assets
7 . filePrefix: 'ipod-', // file prefix if any
8 . ext: '.jpg', // extention for the assets
9 . height: 265,
10 . width: 400,
11 . navigation: true,
12 . disableSpin: true // Default false 
some are optional but maximum things you must have to configure

so in <a href="http://drupal.org/">Drupal(CMS)</a>  as a enduser you are not able to do all these things or very complicated.
we did plain we have to create image field settings like this user just select  <a href="https://github.com/code-rider/drupal_threesixty_slider">drupal_threesixty_slider</a>
and some other settings like height , width , navigation.
and then all nodes from this content type should display as <a href="https://github.com/code-rider/drupal_threesixty_slider">drupal_threesixty_slider</a>.
so in this case we created an edited version of <a href="https://github.com/creativeaura/threesixty-slider">threesixty-slider</a>.

<b>In this case what <a href="https://github.com/creativeaura/threesixty-slider">threesixty-slider</a> do </b>

Drupal render a node with multi valued image field with setting of <a href="https://github.com/code-rider/drupal_threesixty_slider">drupal_threesixty_slider</a>.
when this image field rendered and create a list of images and then our trigger function will be fired and make a request to  <a href="https://github.com/code-rider/drupal_threesixty_slider">drupal_threesixty_slider</a> now <a href="https://github.com/code-rider/drupal_threesixty_slider">drupal_threesixty_slider</a> find the list of image with this settings and fetch all images from list and remove from them and reprocess all image and rebuild a list with all required setting. so <a href="https://github.com/code-rider/drupal_threesixty_slider">drupal_threesixty_slider</a> displayed.

<b> Our achievements </b>

1 . totalFrames: 72, // Total no. of image you have for 360 slider
no need to tell slider we'llcount 
1 . totalFrames: 72, // Total no. of image you have for 360 slider
no need to tell slider we'llcount and set last number of count
2 . endFrame: 72, // end frame for the auto spin animation
no need to tell slider we'llcount and set last number of count
3 . currentFrame: 1, // This the start frame for auto spin
must first number
4 . imgList: '.threesixty_images', // selector for image list
we create this HTML structure in our module 
5 . progress: '.spinner', // selector to show the loading progress
we create this HTML structure in our module
6 . imagePath:'assets/product1/', // path of the image assets
this is the main thing end user not know where <a href="http://drupal.org/">Drupal(CMS)</a> stored all images 
7 . filePrefix: 'ipod-', // file prefix if any
no need to tell slider
8 . ext: '.jpg', // extention for the assets
no need to tell slider
9 . height: 265,
end user able to set height as his web theme 
10 . width: 400,
end user able to set width as his web theme
11 . navigation: true,
end user able to set Navigation should display or not
12 . disableSpin: true // Default false 
no need to tell slider

and one more big achievement with this module you are able to display maximum 20 <a href="https://github.com/code-rider/drupal_threesixty_slider">drupal_threesixty_slider</a>  display at one page.

hope this helps
thanks

**Comment by pepperstreet** [comment]
@code-rider 
Wow. Many thanks for this comprehensive answer. Much more than I could ever expect. Makes absolutely sense now. Great work, great effort. Hopefully, the project will make it into D8 era ;)

Best regards,
Maik

**Comment by code-rider** [comment]
Thanks you @ pepperstreet
for appreciation i am looking forward for D8.
